import Head from 'next/head';
import { useState } from 'react';
import mountainsArray from '../db/mountains.json';

export default function Filtering() {
  const [mountains, setMountains] = useState(mountainsArray);

  //     set search query to empty string
  const [query, setQuery] = useState('');

  //set search parameters
  const [searchParam] = useState(['name', 'effort']);

  function search(items) {
    //returns a copy of items
    //all truthy values get returned
    return items.filter((item) => {
      //callback returns true for items that meet criteria
      //returns truthy value if it passes the citeria
      return searchParam.some((newItem) => {
        // checks for item with property name newItem if it has same query match
        return item[newItem].toString().toLowerCase().includes(query.toLowerCase());
      });
    });
  }

  return (
    <>
      <Head>
        <title>Mountains</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='container-md'>
        <label className='form-label' htmlFor='search-form'>
          Search mountain:
          <input
            className='form-control'
            type='search'
            name='search-form'
            id='search-form'
            value={query}
            onChange={(e) => setQuery(e.target.value)}
            placeholder='Search for...'
          />
        </label>
        <div className='row g-3'>
          {search(mountains).map((mountain) => {
            return (
              <div key={mountain.name} className='col-md-4'>
                <div className='card h-100'>
                  <div className='card-header'>{mountain.name}</div>
                  {/* eslint-disable-next-line @next/next/no-img-element */}
                  <img src='https://placehold.co/600x400.png' alt='placeholder'></img>
                  <div className='card-body'>
                    <div className='card-subtitle text-body-secondary'>
                      {mountain.effort}
                    </div>
                    <div className='card-text'>{mountain.desc}</div>
                  </div>
                </div>
              </div>
            );
          })}
        </div>
      </main>
    </>
  );
}
